services:
  postgres:
    image: postgres:15
    container_name: eglise_postgres
    restart: always
    environment:
      POSTGRES_USER: eglise_user
      POSTGRES_PASSWORD: eglise_pass
      POSTGRES_DB: eglise_db
    ports:
      - "5433:5432"
    volumes:
      - eglise_pg_data:/var/lib/postgresql/data

volumes:
  eglise_pg_data: